
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`default_nettype none
module DE1_SOC(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_DIN,
	input 		          		ADC_DOUT,
	output		          		ADC_SCLK,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

localparam BMP_CTL =  32'hFFFFC008;          // address for BMP Control
localparam BMP_XLOC = 32'hFFFFC009;         // address for BMP X Location
localparam BMP_YLOC = 32'hFFFFC00A;         // address for BMP Y Location
localparam BMP_STAT = 32'hFFFFC00B;         // address for BMP Status 

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire rst_n, clk, pll_locked, debug_sig;
wire [31:0] boot_addr, boot_data;
wire cpu_rst_n;

reg write;
reg [5:0] done;
wire [11:0] joystick_data;

wire [31:0] memMappedAddr, memMappedDataOut;

// VGA
reg [9:0] xloc, yloc;  
wire add_fnt;
wire [5:0] fnt_indx;
wire add_img;
wire [4:0] image_indx;
wire rem_img;
wire busy;

reg we_cpu;

// Debug State Machine
typedef enum reg {IDLE, DEBUG} debug_state_t;
debug_state_t state, nxt_state;

always_ff @(posedge clk, negedge rst_n)
	if(!rst_n)
		state <= IDLE;
	else
		state <= nxt_state;
		
always_comb begin
	nxt_state = state;
	case(state)
		default: if(debug_sig) nxt_state <= DEBUG;
		DEBUG: if(!debug_sig) nxt_state <= IDLE;
	endcase
end


//=======================================================
//  Structural coding
//=======================================================
assign LEDR[8] = !rst_n;
assign LEDR[7] = state;
assign LEDR[5] = !cpu_rst_n;

// Debouncing
reset_synch irst(.RST_n(KEY[0]), .clk(clk), .rst_n(rst_n), .pll_locked(pll_locked));
reset_synch idebug(.RST_n(SW[0]), .clk(clk), .rst_n(debug_sig), .pll_locked(1'b1));

// PLL
pll iPLL (.refclk(CLOCK2_50), .rst(~KEY[0]),.outclk_0(clk),.outclk_1(VGA_CLK),
           .locked(pll_locked));

// Bootloader
bootloader iboot (.clk(clk), .rst_n(rst_n), .debug(state), .addr(boot_addr), .data(boot_data), 
					.increment(LEDR[6]), .RX(GPIO[5]), .TX(GPIO[3]), .outdata(memMappedDataOut), .write(write));

					
assign cpu_rst_n = (state) ? 1'b0 : rst_n;
// CPU
cpu iCPU(.clk(clk), .rst_n(cpu_rst_n), .boot_addr(boot_addr), .boot_data(boot_data), 
			.debug(state), .memMappedAddr(memMappedAddr), .memMappedDataOut(memMappedDataOut), 
			.joystick_data({busy,19'b0,joystick_data}), .halt(LEDR[9]));

// Memory Mapping
always_comb begin
	write = 0;
	done = 'b0;
	we_cpu = 0;
	case(memMappedAddr)
		32'hFFFFC001: 	write = 1;								// TX from bootloader to Macbook
		32'hFFFFC002: 	done = memMappedDataOut[5:0];			// Write to joystick
		BMP_CTL: 		we_cpu = 1;
		BMP_YLOC: 		we_cpu = 1;
		BMP_XLOC: 		we_cpu = 1;
		default: 		write = 0;
	endcase
end

// Joystick
joystick ijoy (.ADC_CONVST(ADC_CONVST), .ADC_DIN(ADC_DIN), .ADC_DOUT(ADC_DOUT), 
					.ADC_SCLK(ADC_SCLK), .clk(clk), .rst_n(rst_n), .done(done), .val(joystick_data));

wire [23:0] seg_addr;
assign seg_addr = (state) ? boot_addr[23:0] : memMappedAddr[23:0];

// Debug : SEG7 display
SEG7_LUT_6 	iseg (.oSEG0(HEX0),.oSEG1(HEX1), .oSEG2(HEX2),.oSEG3(HEX3), .oSEG4(HEX4),.oSEG5(HEX5), .iDIG(boot_addr[23:0]));


// BitMap Display
BMP_display IBMP (.clk(clk), .VGA_CLK(VGA_CLK), .rst_n(rst_n), .VGA_BLANK_N(VGA_BLANK_N), .VGA_B(VGA_B), .VGA_G(VGA_G), .VGA_HS(VGA_HS), .VGA_R(VGA_R), 
					.VGA_SYNC_N(VGA_SYNC_N), .VGA_VS(VGA_VS), .xloc(xloc), .yloc(yloc), .add_fnt(add_fnt), .fnt_indx(fnt_indx), .add_img(add_img), 
					.image_indx(image_indx), .rem_img(rem_img), .busy(busy));

//   // Updating Xloc
always @(posedge clk, negedge rst_n)
    if(!rst_n)
      xloc = 'b0;
    else if((memMappedAddr == BMP_XLOC) && we_cpu) // Qualifying the write
      xloc = memMappedDataOut[9:0];

//   // Update Yloc
always @(posedge clk, negedge rst_n)
    if(!rst_n)
      yloc = 'b0;
    else if((memMappedAddr == BMP_YLOC) && we_cpu) // Qualifying the read
      yloc = memMappedDataOut[9:0];

assign add_fnt = (memMappedAddr === BMP_CTL && we_cpu) ? memMappedDataOut[15] : 1'b0;
assign fnt_indx = (memMappedAddr === BMP_CTL && we_cpu) ? memMappedDataOut[14:9] : 'b0;
assign add_img = (memMappedAddr === BMP_CTL && we_cpu) ? memMappedDataOut[6] : 'b0;
assign image_indx = (memMappedAddr === BMP_CTL  && we_cpu) ? memMappedDataOut[4:0] : 5'h01;
assign rem_img = (memMappedAddr === BMP_CTL && we_cpu) ? memMappedDataOut[5] : 1'b0;



endmodule
