onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /MiniLab1_tb/iDUT/clk
add wave -noupdate /MiniLab1_tb/iDUT/RST_n
add wave -noupdate /MiniLab1_tb/iDUT/RX
add wave -noupdate /MiniLab1_tb/iDUT/SW
add wave -noupdate /MiniLab1_tb/iDUT/LED
add wave -noupdate /MiniLab1_tb/iDUT/TX
add wave -noupdate /MiniLab1_tb/iDUT/rst_n
add wave -noupdate /MiniLab1_tb/iDUT/wdata
add wave -noupdate /MiniLab1_tb/iDUT/rdataSW
add wave -noupdate /MiniLab1_tb/iDUT/rdata
add wave -noupdate /MiniLab1_tb/iDUT/ex_we
add wave -noupdate /MiniLab1_tb/iDUT/ex_re
add wave -noupdate /MiniLab1_tb/iDUT/addr
add wave -noupdate /MiniLab1_tb/iDUT/iocs_n
add wave -noupdate /MiniLab1_tb/iDUT/iorw_n
add wave -noupdate /MiniLab1_tb/iDUT/tx_q_full
add wave -noupdate /MiniLab1_tb/iDUT/rx_q_empty
add wave -noupdate /MiniLab1_tb/iDUT/spart_databus
add wave -noupdate /MiniLab1_tb/iDUT/spart_databus_logic
add wave -noupdate /MiniLab1_tb/iDUT/ioaddr
add wave -noupdate -divider -height 30 SPART
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/clk
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/rst_n
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/iocs_n
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/iorw_n
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/tx_q_full
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/rx_q_empty
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/ioaddr
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/databus
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/TX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/RX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/baudrate
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/read_pointer_RX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/write_pointer_RX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/read_pointer_TX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/write_pointer_TX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/rx_data
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/tx_data
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/rdy
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/tx_done
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/trmt
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/clr_rdy
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/flop_rdy
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/first_time_TX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/databus_logic
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/rx_q_full
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/tx_q_empty
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/circular_buffer_RX
add wave -noupdate /MiniLab1_tb/iDUT/iSPART/circular_buffer_TX
add wave -noupdate -divider -height 30 {Test Rx}
add wave -noupdate /MiniLab1_tb/iRX/baudrate
add wave -noupdate /MiniLab1_tb/iRX/clk
add wave -noupdate /MiniLab1_tb/iRX/rst_n
add wave -noupdate /MiniLab1_tb/iRX/RX
add wave -noupdate /MiniLab1_tb/iRX/clr_rdy
add wave -noupdate /MiniLab1_tb/iRX/rdy
add wave -noupdate /MiniLab1_tb/iRX/rx_data
add wave -noupdate /MiniLab1_tb/iRX/state
add wave -noupdate /MiniLab1_tb/iRX/nxt_state
add wave -noupdate /MiniLab1_tb/iRX/rx_shift_reg
add wave -noupdate /MiniLab1_tb/iRX/bit_cnt
add wave -noupdate /MiniLab1_tb/iRX/baud_cnt
add wave -noupdate /MiniLab1_tb/iRX/RX_temp1
add wave -noupdate /MiniLab1_tb/iRX/RX_temp2
add wave -noupdate /MiniLab1_tb/iRX/start
add wave -noupdate /MiniLab1_tb/iRX/set_rdy
add wave -noupdate /MiniLab1_tb/iRX/receiving
add wave -noupdate /MiniLab1_tb/iRX/shift
add wave -noupdate -divider -height 30 {CPU sigs}
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/clk
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rst_n
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rdata
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/wdata
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/addr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/ex_re
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/ex_we
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/DM_we
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dm_rd_data_EX_DM_in
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/instr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/instr_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/src0
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/src1
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dst_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dst_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/iaddr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/pc_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/pc_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/stall_IM_ID
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/stall_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/stall_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dm_rd_data_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_w_data_DM_WB
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/p0
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/p1
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_p0_addr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_p1_addr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_dst_addr_DM_WB
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/alu_func_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/src0sel_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/src1sel_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/cc_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/p0_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/flow_change_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/zr_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/br_instr_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/jmp_imm_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/jmp_reg_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/jmp_imm_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_re0
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_re1
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/rf_we_DM_WB
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dm_re_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/dm_we_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/clk_z_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/clk_nv_ID_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/hlt_DM_WB
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/byp0_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/byp0_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/byp1_EX
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/byp1_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/ov
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/zr
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/neg
add wave -noupdate -divider -height 30 {Stall logic in ID}
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/iID/dst_EX_DM
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/iID/dm_re
add wave -noupdate /MiniLab1_tb/iDUT/iCPU/iID/flush
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {24 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 444
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {48 ns}
