$(HDL_PATH)/riscv_pkg.sv
$(HDL_PATH)/decode.sv
$(HDL_PATH)/execute.sv
$(HDL_PATH)/fetch.sv
$(HDL_PATH)/memory.sv
$(HDL_PATH)/write_back.sv
$(HDL_PATH)/pipeline.sv
$(HDL_PATH)/register_file.sv
$(HDL_PATH)/proc.sv
$(HDL_PATH)/core.sv
$(HDL_PATH)/DRAMIdeal.v
$(HDL_PATH)/DRAMStall.v
../riscv_reg_comp_if.sv
../../fpga/wiscv_wrapper.sv
../../fpga/UART.v
../../fpga/UART_tx.v
../../fpga/UART_rcv.sv
../../fpga/clk_div.sv
